apiVersion: meta.pkg.crossplane.io/v1alpha1
kind: Configuration
metadata:
  name: configuration-azure-aks
  annotations:
    meta.crossplane.io/maintainer: Upbound <support@upbound.io>
    meta.crossplane.io/source: github.com/upbound/configuration-azure-aks
    meta.crossplane.io/license: Apache-2.0
    meta.crossplane.io/description: |
      Azure AKS Configuration is reusable Configuration designed to be primarily used in higher level Configurations.
    meta.crossplane.io/readme: |
      This configuration bundles an Upbound Cloud extension and an API definition. This API allows control planes to provision Azure AKS clusters, composed using cloud service primitives from the Upbound Official Providers

spec:
  crossplane:
    version: ">=v1.14.1-0"
  dependsOn:
    - provider: xpkg.upbound.io/upbound/provider-azure-containerservice
      version: "v1"
    - configuration: xpkg.upbound.io/upbound/configuration-azure-network
      # renovate: datasource=github-releases depName=upbound/configuration-azure-network
      version: "v0.13.0"
    - provider: xpkg.upbound.io/upbound/provider-helm
      version: "v0"
    - provider: xpkg.upbound.io/upbound/provider-kubernetes
      version: "v0"
    - function: xpkg.upbound.io/crossplane-contrib/function-patch-and-transform
      # renovate: datasource=github-releases depName=crossplane-contrib/function-patch-and-transform
      version: "v0.8.1"
