apiVersion: azure.platform.upbound.io/v1alpha1
kind: XAKS
metadata:
  name: configuration-azure-aks
spec:
  parameters:
    id: configuration-azure-aks
    region: westus
    version: "1.31"
    nodes:
      count: 1
      instanceType: Standard_B2s
  writeConnectionSecretToRef:
    name: configuration-azure-aks-kubeconfig
    namespace: upbound-system
