apiVersion: azure.platform.upbound.io/v1alpha1
kind: AKS
metadata:
  name: configuration-azure-aks
  namespace: default
spec:
  parameters:
    id: configuration-azure-aks
    region: westus
    version: "1.34"
    nodes:
      count: 1
      instanceType: Standard_B2s
