name: CI

on:
  push:
    branches:
      - main
  pull_request: {}
  workflow_dispatch:
    inputs:
      version:
        description: Package version (e.g. v0.1.0)
        required: false

env:
  UP_API_TOKEN: ${{ secrets.UP_API_TOKEN }}
  UP_ORG: ${{ secrets.UP_ORG }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Install and login with up
        if: env.UP_API_TOKEN != '' && env.UP_ORG != ''
        uses: upbound/action-up@53fe6395637d884c80d2bbc8c2d75d0ece776ced # v1
        with:
          api-token: ${{ secrets.UP_API_TOKEN }}
          organization: ${{ secrets.UP_ORG }}

      - name: Build and Push Upbound project
        if: env.UP_API_TOKEN != ''
        uses: upbound/action-up-project@87016022642d4076f1360639bdf0f04527c28983 # v1
        with:
          push-project: true
          tag: ${{ inputs.version || '' }}
